--- 
language: cpp
matrix: 
  include: 
    - 
      before_install:
        - "sudo apt-get install qt5-default"
      compiler: gcc
      dist: trusty
      os: linux
      script: 
        - "$CXX -o cpf -std=c++14 CreatePoolFile/CreatePoolFile.cpp"
        - "./cpf TEX_STRING rstex.cpp.pre rstex.h.pre"
        - "$CXX -o rstex -std=c++14 rstex.cpp"
        - "./cpf TEX_STRING rstex_unix/rstex.cpp.pre rstex_unix/rstex.h.pre"
        - "$CXX -o rstex -std=c++14 rstex_unix/rstex.cpp"
        - "cd TeXFontViewerQt"
        - "qmake QMAKE_CXX=$CXX QMAKE_LINK=$CXX TeXFontViewerQt.pro"
        - make
        - "cd .."
    - 
      before_install:
        - "sudo apt-get install qt5-default"
      compiler: clang
      dist: trusty
      os: linux
      script:
        - ./build.sh
        - "cd rstex_unix"
        - ./build.sh
        - "cd TeXFontViewerQt"
        - ./build.sh
        - "cd .."
    - 
      os: windows
      script:
        - "echo \"Starting windows build..\""
        - ./build.bat
        - "cd rsmetafont_win"
        - ./build.bat
        - "cd ../rsgftodvi_win"
        - ./build.bat
        - "cd ../dviviewer_win"
        - ./build.bat
        - "cd ../rstex_win"
        - ./build.bat
        - "cd ../rsdvitype_win"
        - ./build.bat
        - "cd ../rsetex_win"
        - ./build.bat
        - "cd .."
