--- 
language: cpp
matrix: 
  include: 
    - 
      before_install:
        - "sudo apt-get install qt5-default"
      compiler: gcc
      dist: trusty
      os: linux
      script: 
        - ./build.sh
        - "cd rstex_unix"
        - ./build.sh
        - "cd ../TeXFontViewerQt"
        - ./build.sh
        - "cd ../rsetex_unix"
        - ./build.sh
        - "cd ../rsgftodvi_unix"
        - ./build.sh
        - "cd ../rsdvitype_unix"
        - ./build.sh
        - "cd ../rsmetafont_unix"
        - ./build.sh
        - "cd .."
    - 
      before_install:
        - "sudo apt-get install qt5-default"
      compiler: clang
      dist: trusty
      os: linux
      script:
        - ./build.sh
        - "cd rstex_unix"
        - ./build.sh
        - "cd ../TeXFontViewerQt"
        - ./build.sh
        - "cd ../rsetex_unix"
        - ./build.sh
        - "cd ../rsgftodvi_unix"
        - ./build.sh
        - "cd ../rsdvitype_unix"
        - ./build.sh
        - "cd ../rsmetafont_unix"
        - ./build.sh
        - "cd .."
    - 
      os: windows
      script:
        - "echo \"Starting windows build..\""
        - ./build.bat
        - "cd rsmetafont_win"
        - ./build.bat
        - "cd ../rsgftodvi_win"
        - ./build.bat
        - "cd ../dviviewer_win"
        - ./build.bat
        - "cd ../rstex_win"
        - ./build.bat
        - "cd ../rsdvitype_win"
        - ./build.bat
        - "cd ../rsetex_win"
        - ./build.bat
        - "cd .."
